# Generated by Django 5.2.17 on 2026-09-08 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField(db_index=True)),
                ('responsable', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Conteo físico',
                'verbose_name_plural': 'Conteos físicos',
                'ordering': ['-fecha_corte'],
            },
        ),
        migrations.CreateModel(
            name='CostoAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.DateField(db_index=True, help_text='Usar el primer día del mes correspondiente')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Costo de almacenamiento',
                'verbose_name_plural': 'Costos de almacenamiento',
                'ordering': ['-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(db_index=True)),
                ('cliente', models.CharField(max_length=200)),
                ('canal', models.CharField(choices=[('mostrador', 'Mostrador'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('presentacion', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('lead_time_dias', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('lead_time_promedio', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_atendida', models.IntegerField(default=0)),
                ('fecha_atencion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('atendido_a_tiempo', models.BooleanField(default=False)),
                ('motivo_no_atencion', models.CharField(blank=True, choices=[('sin_stock', 'Sin stock'), ('llego_tarde', 'Llegó tarde'), ('otro', 'Otro')], max_length=20, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_detalles', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
                'indexes': [models.Index(fields=['pedido', 'producto'], name='inventario__pedido__e2f282_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(db_index=True)),
                ('documento', models.CharField(blank=True, max_length=100)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='inventario__product_07599f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(db_index=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='inventario__product_9acf7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConteoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField()),
                ('stock_fisico', models.IntegerField()),
                ('diferencia', models.IntegerField(editable=False)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.conteofisico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteo_detalles', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de conteo',
                'verbose_name_plural': 'Detalles de conteo',
                'indexes': [models.Index(fields=['conteo', 'producto'], name='inventario__conteo__563b65_idx')],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(db_index=True)),
                ('fecha_llegada', models.DateField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_pedido'],
                'indexes': [models.Index(fields=['proveedor', 'fecha_pedido'], name='inventario__proveed_020a7a_idx')],
            },
        ),
    ]
