# Generated by Django 5.2.17 on 2026-09-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='stock_anterior',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
