# Generated by Django 5.2.17 on 2026-09-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento_stock_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteofisico',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='prueba', max_length=10),
        ),
        migrations.AddField(
            model_name='costoalmacenamiento',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='prueba', max_length=10),
        ),
        migrations.AddField(
            model_name='merma',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='prueba', max_length=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='prueba', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='prueba', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='prueba', max_length=10),
        ),
    ]
