# Generated by Django 5.2.17 on 2026-09-11 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_conteofisico_origen_costoalmacenamiento_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fase', models.CharField(choices=[('base', 'Base (preentrenado)'), ('ajustado', 'Ajustado (transferencia)')], db_index=True, max_length=10)),
                ('algoritmo', models.CharField(default='XGBRegressor', max_length=100)),
                ('hiperparametros', models.JSONField()),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('r2', models.FloatField()),
                ('mae_linea_base', models.FloatField(blank=True, null=True)),
                ('mae_solo_interno', models.FloatField(blank=True, null=True)),
                ('n_registros_externos', models.IntegerField(default=0)),
                ('n_registros_internos', models.IntegerField(default=0)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo entrenado',
                'verbose_name_plural': 'Modelos entrenados',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_objetivo', models.DateField(db_index=True)),
                ('demanda_predicha', models.FloatField()),
                ('demanda_real', models.FloatField(blank=True, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predicciones', to='inventario.modeloentrenado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha_objetivo'],
                'indexes': [models.Index(fields=['producto', 'fecha_objetivo'], name='inventario__product_5c70c1_idx')],
            },
        ),
    ]
