# Generated by Django 5.2.17 on 2026-09-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_modeloentrenado_prediccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_llegada_linea', models.DateField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_detalles', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
                'indexes': [models.Index(fields=['producto', 'compra'], name='inventario__product_4fc604_idx')],
            },
        ),
    ]
