# Generated by Django 5.2.17 on 2026-09-11 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_compradetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('critico', 'Crítico'), ('reponer', 'Reponer'), ('normal', 'Normal'), ('exceso', 'Exceso')], db_index=True, max_length=10)),
                ('stock_actual_snapshot', models.IntegerField()),
                ('demanda_predicha_periodo', models.FloatField()),
                ('desviacion_demanda', models.FloatField()),
                ('lead_time_usado', models.FloatField()),
                ('stock_seguridad', models.FloatField()),
                ('punto_reorden', models.FloatField()),
                ('cantidad_sugerida', models.FloatField()),
                ('nivel_servicio_objetivo', models.FloatField()),
                ('explicacion', models.TextField()),
                ('aceptada', models.BooleanField(blank=True, null=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['producto', 'fecha_generacion'], name='inventario__product_4c7557_idx')],
            },
        ),
    ]
