# Generated by Django 5.2.17 on 2026-09-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='fecha_generacion',
            field=models.DateTimeField(db_index=True),
        ),
    ]
