# Generated by Django 5.2.17 on 2026-09-11 05:06

import django.core.validators
from django.db import migrations, models


def corregir_lead_time_en_cero(apps, schema_editor):
    """La importación (cargar_datos) dejó productos con lead_time_dias=0,
    porque el Excel no trae ese dato. El CheckConstraint que se agrega en
    esta misma migración exige lead_time_dias > 0, así que hay que corregir
    esas filas antes de crearlo o la migración fallaría contra datos ya
    cargados. Se puede volver a ajustar después con el comando
    "configurar_lead_time"."""
    Producto = apps.get_model('inventario', 'Producto')
    Producto.objects.filter(lead_time_dias=0).update(lead_time_dias=7)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_prediccion_fecha_generacion'),
    ]

    operations = [
        migrations.RunPython(corregir_lead_time_en_cero, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='producto',
            name='lead_time_dias',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1, message='El lead time debe ser mayor a 0 días.')]),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('lead_time_dias__gt', 0)), name='producto_lead_time_dias_positivo'),
        ),
    ]
