# Generated by Django 5.2.17 on 2026-09-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_producto_lead_time_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha_generacion',
            field=models.DateTimeField(db_index=True),
        ),
    ]
