# Generated by Django 5.2.17 on 2026-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_recomendacion_fecha_generacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeloentrenado',
            old_name='mape',
            new_name='smape',
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='nivel',
            field=models.CharField(choices=[('producto', 'Producto'), ('categoria', 'Categoría')], db_index=True, default='producto', max_length=10),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='nivel_prediccion',
            field=models.CharField(choices=[('producto', 'Producto'), ('categoria', 'Categoría')], default='producto', max_length=10),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='participacion_usada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('latex', 'Látex'), ('esmalte', 'Esmalte'), ('temple', 'Temple'), ('solvente', 'Solvente'), ('accesorio', 'Accesorio'), ('base', 'Base'), ('otro', 'Otro')], db_index=True, default='otro', max_length=10),
        ),
    ]
