# Generated by Django 5.2.17 on 2026-09-17 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_rename_mape_modeloentrenado_smape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deteccion', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(choices=[('diferencia_inventario', 'Diferencia de inventario'), ('movimiento_atipico', 'Movimiento atípico')], db_index=True, max_length=25)),
                ('severidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], db_index=True, max_length=10)),
                ('score', models.FloatField()),
                ('valor_observado', models.FloatField()),
                ('valor_esperado', models.FloatField()),
                ('descripcion', models.TextField()),
                ('revisada', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Anomalía',
                'verbose_name_plural': 'Anomalías',
                'ordering': ['-fecha_deteccion'],
                'indexes': [models.Index(fields=['producto', 'fecha_deteccion'], name='inventario__product_197798_idx')],
            },
        ),
    ]
