# Generated by Django 5.2.17 on 2026-09-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_anomalia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='fecha_requerida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
