# Generated by Django 5.2.17 on 2026-09-21 01:30

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_pedidodetalle_fecha_requerida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # CREATE EXTENSION IF NOT EXISTS vector: necesaria para el
        # VectorField de DocumentoIndexado. Ya está creada a mano en la
        # base de datos de desarrollo, pero se deja aquí para que
        # "migrate" la cree sola en cualquier otro entorno (incluida la
        # base de datos de test).
        VectorExtension(),
        migrations.CreateModel(
            name='ConsultaAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('documentos_usados', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta al asistente',
                'verbose_name_plural': 'Consultas al asistente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoIndexado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('recomendacion', 'Recomendación'), ('anomalia', 'Anomalía'), ('indicador', 'Indicador'), ('modelo', 'Estado del modelo')], db_index=True, max_length=20)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('fecha_indexacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento indexado',
                'verbose_name_plural': 'Documentos indexados',
                'indexes': [models.Index(fields=['tipo', 'referencia_id'], name='inventario__tipo_f30d9e_idx')],
            },
        ),
    ]
