# Generated by Django 5.2.17 on 2026-09-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_consultaasistente_documentoindexado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoindexado',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('recomendacion', 'Recomendación'), ('anomalia', 'Anomalía'), ('indicador', 'Indicador'), ('modelo', 'Estado del modelo'), ('resumen_categoria', 'Resumen por categoría'), ('resumen_estado', 'Resumen de estados del catálogo'), ('resumen_anomalias', 'Resumen de anomalías')], db_index=True, max_length=20),
        ),
    ]
