# Generated by Django 5.2.17 on 2026-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_documentoindexado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloentrenado',
            name='origen_datos_internos',
            field=models.CharField(blank=True, choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, max_length=10, null=True),
        ),
    ]
