# Generated by Django 5.2.17 on 2026-09-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_modeloentrenado_origen_datos_internos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloentrenado',
            name='dias_entrenamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='dias_prueba',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
