# Generated by Django 5.2.17 on 2026-09-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_modeloentrenado_dias_entrenamiento_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalia',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_detectadas', to='inventario.movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='stock_resultante',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
