# Generated by Django 5.2.17 on 2026-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_anomalia_movimiento_movimiento_stock_resultante'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloentrenado',
            name='descartado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='motivo_descarte',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='r2_linea_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='r2_solo_interno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='rmse_linea_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='rmse_solo_interno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='smape_linea_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='smape_solo_interno',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
