# Generated by Django 5.2.17 on 2026-09-24 21:54

import django.db.models.deletion
import re
from datetime import datetime

from django.db import migrations, models

# Formato de la descripción anterior de una diferencia de inventario:
# "PIN-259 — Anypsa Gloss: el conteo físico del 24/08/2026 encontró ...".
PATRON_FECHA_CONTEO = re.compile(r'conteo físico del (\d{2}/\d{2}/\d{4})')


def vincular_conteo_detalle(apps, schema_editor):
    """Enlaza cada anomalía de diferencia de inventario ya existente con el
    ConteoDetalle que la originó (mismo producto, misma fecha de corte y
    misma diferencia). Las que no se puedan enlazar quedan sin conteo; volver
    a correr "detectar_anomalias" crea su versión enlazada."""
    Anomalia = apps.get_model('inventario', 'Anomalia')
    ConteoDetalle = apps.get_model('inventario', 'ConteoDetalle')
    for anomalia in Anomalia.objects.filter(tipo='diferencia_inventario', conteo_detalle__isnull=True):
        coincidencia = PATRON_FECHA_CONTEO.search(anomalia.descripcion)
        if not coincidencia:
            continue
        fecha_corte = datetime.strptime(coincidencia.group(1), '%d/%m/%Y').date()
        candidatos = list(ConteoDetalle.objects.filter(
            producto_id=anomalia.producto_id, conteo__fecha_corte=fecha_corte,
            diferencia=round(anomalia.valor_observado),
        )[:2])
        if len(candidatos) == 1:
            anomalia.conteo_detalle = candidatos[0]
            anomalia.save(update_fields=['conteo_detalle'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_modeloentrenado_comparacion_descartado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalia',
            name='conteo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='inventario.conteodetalle'),
        ),
        migrations.AddField(
            model_name='anomalia',
            name='detalle_revision',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anomalia',
            name='motivo_revision',
            field=models.CharField(blank=True, choices=[('error_conteo', 'Error de conteo'), ('ingreso_no_registrado', 'Ingreso no registrado'), ('merma_no_anotada', 'Merma no anotada'), ('otro', 'Otro')], db_index=True, max_length=25),
        ),
        migrations.RunPython(vincular_conteo_detalle, migrations.RunPython.noop),
    ]
