# Generated by Django 5.2.17 on 2026-09-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_anomalia_conteo_detalle_motivo_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='demanda_categoria_periodo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='dias_horizonte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='lead_time_es_real',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='participacion_usada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='pedidos_en_transito',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
