# Generated by Django 5.2.17 on 2026-09-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_pedidodetalle_precios_no_nulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaasistente',
            name='fallo_llm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultaasistente',
            name='modelo_llm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consultaasistente',
            name='proveedor_llm',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
