# Generated by Django 5.2.17 on 2026-09-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_consultaasistente_proveedor_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoindexado',
            name='origen',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('real', 'Real')], db_index=True, default='real', max_length=10),
        ),
    ]
