# Generated by Django 5.2.17 on 2026-09-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_documentoindexado_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='origen_demanda',
            field=models.CharField(blank=True, choices=[('prueba', 'Prueba'), ('real', 'Real')], max_length=10, null=True),
        ),
    ]
