# Generated by Django 5.2.17 on 2026-09-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_recomendacion_origen_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='demanda_diaria_historica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='fecha_corte_historico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='metodo',
            field=models.CharField(choices=[('pronostico', 'Pronóstico'), ('punto_reorden', 'Punto de reorden')], db_index=True, default='pronostico', max_length=15),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='stock_minimo_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='demanda_predicha_periodo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
