# Generated by Django 5.2.17 on 2026-10-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_recomendacion_metodo_fecha_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloentrenado',
            name='acierto_tolerancia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='exactitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='exactitud_mejor_linea_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='mejor_linea_base',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='metricas_mejor_linea_base',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='r2_intra_categoria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='tolerancia_relativa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='wape',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloentrenado',
            name='wape_mejor_linea_base',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
