"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost,http://127.0.0.1',
    cast=Csv()
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inventario.context_processors.datos_globales',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autenticación: el dashboard requiere login.
# https://docs.djangoproject.com/en/5.2/topics/auth/default/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inventario:dashboard'
LOGOUT_REDIRECT_URL = 'login'


# Asistente conversacional (RAG)
# ------------------------------
# Proveedor del modelo de lenguaje: por ahora Ollama local (los datos de la
# microempresa nunca salen del equipo), con una interfaz común
# (inventario/asistente/proveedores.py) para poder pasar a una API externa
# más adelante cambiando solo estas variables, sin tocar el resto del
# módulo.
LLM_PROVEEDOR = config('LLM_PROVEEDOR', default='ollama')
LLM_MODELO = config('LLM_MODELO', default='qwen2.5:7b')
LLM_URL = config('LLM_URL', default='http://localhost:11434')

# Razón social de la microempresa: si aparece en algún documento del RAG, el
# anonimizador la redacta antes de enviar cualquier dato a la API del
# modelo de lenguaje (inventario/asistente/anonimizador.py). Opcional.
EMPRESA_RAZON_SOCIAL = config('EMPRESA_RAZON_SOCIAL', default='')

# Detección de anomalías
# ----------------------
# Umbrales de severidad de una diferencia de inventario, como fracción de
# la diferencia sobre el stock de sistema (1.0 = 100%): alta desde
# ANOMALIA_UMBRAL_ALTA (inclusive: un faltante total, físico en 0, es
# exactamente 100%), media desde ANOMALIA_UMBRAL_MEDIA, baja por debajo. Tras cambiarlos, correr
# "detectar_anomalias" recalcula la severidad de las anomalías existentes.
ANOMALIA_UMBRAL_ALTA = config('ANOMALIA_UMBRAL_ALTA', default=1.0, cast=float)
ANOMALIA_UMBRAL_MEDIA = config('ANOMALIA_UMBRAL_MEDIA', default=0.40, cast=float)
